#!/usr/bin/env ruby

# frozen_string_literal: true

require_relative 'mysql_database_config'
require_relative 'mysql_database_backup'
require_relative 'loggman'

config_file = 'config.json'
logger = Loggman.new

begin
  if ARGV[0] == '--restore'
    # Call your restore function here with backup_id
    logger.info("Restoring backup with ID: #{backup_id}")
    
  else
    logger.info('Starting script.')

    config_generator = MysqlDatabaseConfig.new(config_file)
    config_generator.generate
    logger.info("Generated MySQL database configuration file: #{config_file}.")

    backup = MysqlDatabaseBackup.new(config_file)
    backup.backup
    logger.info('Performed MySQL database backup.')

    logger.info('Script completed successfully.')
  end
rescue StandardError => e
  logger.error("An error occurred: #{e.message}")
  logger.debug("Backtrace: #{e.backtrace}")
end
